name: "Generate README example list"

on: [pull_request]
jobs:
  readme-generator:
    name: Generate README example list
    runs-on: ubuntu-latest

    steps:
    - name: Prepare repository
      uses: actions/checkout@v2

    - name: Prepare Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "16"

    - name: Prepare function
      run: |
        cd github/workflows/examples-list-workflow
        npm install

    - name: Run function
      run: node index.js

    - name: Push changes
      run: |
        git config --global user.name 'README automation'
        git config --global user.email 'security@appwrite.io'
        git commit -am "Automated README generation"
        git push