name: "Generate README example list"

on: [pull_request]
jobs:
  readme-generator:
    runs-on: ubuntu-latest

    steps:
    - name: Prepare repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Prepare Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "16"

    - name: Prepare function
      run: |
        cd .github/workflows/examples-list-workflow
        npm install

    - name: Run function
      run: cd .github/workflows/examples-list-workflow && node index.js

    - name: Push changes
      run: |
        git config user.name github-actions
        git config user.email security@appwrite.io
        git add README.md
        git commit -m "Automated README generation"
        git push